ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "creatorFirstName" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "creatorLastName" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "creatorUsername" TEXT;
